apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: python-service-a
        image: your-python-image-a:latest
        ports:
        - containerPort: 5000
        env:
        - name: SERVICE_B_URL
          value: "http://service-b"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: python-service-b
        image: your-python-image-b:latest
        ports:
        - containerPort: 5000
        env:
        - name: SERVICE_A_URL
          value: "http://service-a"